# Proyecto 2
Estuardo Díaz 16110

In [12]:
import numpy as np
from scipy import linalg

### Factorización $LU$ de matrices

In [13]:
def factorizar(A):
    PL, U = linalg.lu(A,True)
    return PL, U

## a) Matriz mal condicionada

Definimos la **condición** de $A$ como $cond(A) := ||A||\cdot ||A^{-1}||$

In [14]:
def cond(A):
    inv_A = linalg.inv(A)
    return linalg.norm(A)*linalg.norm(inv_A)

Consideremos la matriz $H$ mal condicionada siguiente:

La matriz de Hilbert es una matriz $H$ de $n\times n$ cuyas entradas están dadas por $$H_{ij} = \frac{1}{i+j-1}$$  

In [30]:
def getHilbertMatrix(n = 5):
    H = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            H[i,j] = 1/(i+j+1)
    return H


In [38]:
H = getHilbertMatrix()
H

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [39]:
print("cond(H): ",cond(H))

cond(H):  480849.1169943362


Como la condición de $H$ es muy grande, sabemos que la matriz es mal condicionada. Por lo tanto, la factorización no es buena.

In [43]:
PL, U = factorizar(H)
print("Norma de (PL*U - H): ", linalg.norm(PL*U - H))
print("PL*U - H:")
PL*U - H

Norma de (PL*U - H):  1.468201940443891
PL*U - H:


array([[ 0.        , -0.5       , -0.33333333, -0.25      , -0.2       ,
        -0.16666667, -0.14285714, -0.125     , -0.11111111, -0.1       ],
       [-0.5       , -0.25      , -0.32619048, -0.11666667, -0.16666667,
        -0.14285714, -0.125     , -0.11111111, -0.1       , -0.09090909],
       [-0.33333333, -0.25      , -0.2       , -0.16666667, -0.14285714,
        -0.125     , -0.11111111, -0.1       , -0.09090909, -0.08333333],
       [-0.25      , -0.2       , -0.16666667, -0.14318182, -0.12321429,
        -0.11013676, -0.0957483 , -0.09090909, -0.08333333, -0.07692308],
       [-0.2       , -0.16666667, -0.14285714, -0.125     , -0.11115646,
        -0.1       , -0.09090909, -0.08333333, -0.07692308, -0.07142857],
       [-0.16666667, -0.14285714, -0.125     , -0.11111111, -0.1       ,
        -0.09091008, -0.08333948, -0.07689908, -0.07142857, -0.06666667],
       [-0.14285714, -0.125     , -0.11111111, -0.1       , -0.09090909,
        -0.08333333, -0.07692303, -0.07142905

Si lo calculamos para $H$ con $n=10$ obtenemos aún resultados similares:

In [45]:
H = getHilbertMatrix(10)
print("cond(H): ",cond(H))
PL, U = factorizar(H)
print("Norma de (PL*U - H): ", linalg.norm(PL*U - H))
print("PL*U - H:")
PL*U - H

cond(H):  16331839891317.996
Norma de (PL*U - H):  1.468201940443891
PL*U - H:


array([[ 0.        , -0.5       , -0.33333333, -0.25      , -0.2       ,
        -0.16666667, -0.14285714, -0.125     , -0.11111111, -0.1       ],
       [-0.5       , -0.25      , -0.32619048, -0.11666667, -0.16666667,
        -0.14285714, -0.125     , -0.11111111, -0.1       , -0.09090909],
       [-0.33333333, -0.25      , -0.2       , -0.16666667, -0.14285714,
        -0.125     , -0.11111111, -0.1       , -0.09090909, -0.08333333],
       [-0.25      , -0.2       , -0.16666667, -0.14318182, -0.12321429,
        -0.11013676, -0.0957483 , -0.09090909, -0.08333333, -0.07692308],
       [-0.2       , -0.16666667, -0.14285714, -0.125     , -0.11115646,
        -0.1       , -0.09090909, -0.08333333, -0.07692308, -0.07142857],
       [-0.16666667, -0.14285714, -0.125     , -0.11111111, -0.1       ,
        -0.09091008, -0.08333948, -0.07689908, -0.07142857, -0.06666667],
       [-0.14285714, -0.125     , -0.11111111, -0.1       , -0.09090909,
        -0.08333333, -0.07692303, -0.07142905

## b) Matriz de insumo producto

La matriz de insumo-producto es una matriz que representa las compras y ventas de varios sectores de economía y se utilizan para predecir demanda o la producción que se requiere para satisfacer la demanda.

En este ejemplo, $A$ es la matriz de insumo producto sobre los sectores de Agricultura, Industria y Servicios. La variable $y$ representa la demanda y queremos calcular $x$, la producción bruta.
\begin{align}
x &= Ax + y \\
x - Ax &= y \\
x(I - A) &= y\\
x &= (I-A)^{-1}y
\end{align}

In [113]:
A = np.array([[0.2, 0.1, 0.2],[0.5, 0.2, 0.1],[0.3, 0.7, 0.1]])
print("A:\n",A)

A:
 [[0.2 0.1 0.2]
 [0.5 0.2 0.1]
 [0.3 0.7 0.1]]


In [114]:
y = np.array([[600],[1000],[700]])
print("y:\n",y)

y:
 [[ 600]
 [1000]
 [ 700]]


Llamamos la la matriz $(I-A)$ la matriz de Leontief y $(I-A)^{-1}$ la matriz inversa de Leontief

In [115]:
Leontief = np.identity(3)- A
print("Matriz de Leontief:\n", Leontief)
print("Matriz inversa de Leontief:\n", linalg.inv(Leontief))

Matriz de Leontief:
 [[ 0.8 -0.1 -0.2]
 [-0.5  0.8 -0.1]
 [-0.3 -0.7  0.9]]
Matriz inversa de Leontief:
 [[1.83615819 0.64971751 0.48022599]
 [1.3559322  1.86440678 0.50847458]
 [1.66666667 1.66666667 1.66666667]]


In [96]:
x = Leontief.dot(y)
x

array([[2087.57062147],
       [3033.89830508],
       [3833.33333333]])

Notamos que la solución es efectivamente correcta

In [106]:
print("x - (Ax+y):")
print(x-(A.dot(x)+y))

x - (Ax+y):
[[ 0.00000000e+00]
 [ 4.54747351e-13]
 [-4.54747351e-13]]


## c) Regresión múltiple

In [19]:
A = np.array([[2.0,4.0,5.0],[6.0,9.0,8.0],[4.1,5.0,3.0]])

### Referencias
* Weisstein, Eric W. "Hilbert Matrix." From MathWorld--A Wolfram Web Resource. http://mathworld.wolfram.com/HilbertMatrix.html
* Prof. Waldo Marquez González, "La Matriz de Leontief", EL PROBLEMA ECONOMICO DE LAS RELACIONES INTERINDUSTRIALES. http://www.ehu.eus/Jarriola/Docencia/EcoEsp/matriz-de-leontief.pdf